/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Marcio Almeida
 */
public class InicioAreaSujaGUI extends javax.swing.JFrame {

    private JPanel panelPedidos;
    private List<JButton> botoesPedidos;
    private int contadorPedidos;

    public InicioAreaSujaGUI() {
        initComponents();

        // Lista de botões de pedidos
        botoesPedidos = new ArrayList<>();
        contadorPedidos = 1;

        //cria o primeiro botão
        JButton novoPedido = new JButton("Novo Pedido");
        novoPedido.setFont(new Font("Arial", Font.BOLD, 24)); // Define a fonte e o tamanho do texto
        novoPedido.setVisible(true); // Inicialmente invisível
        botoesPedidos.add(novoPedido);
        jPanel1.add(novoPedido);

        novoPedido.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                adicionarNovoPedido();
            }
        });

        // Cria os botões iniciais como invisíveis
        for (int i = 1; i < 8; i++) {
            JButton botaoPedido = new JButton();
            botaoPedido.setFont(new Font("Arial", Font.BOLD, 24)); // Define a fonte e o tamanho do texto
            botaoPedido.setVisible(false); // Inicialmente invisível
            botoesPedidos.add(botaoPedido);
            botaoPedido.setLayout(new GridLayout(3, 1)); // Define um layout de grade para organizar os rótulos
            JLabel cliente = new JLabel("Cliente");
            botaoPedido.add(cliente, BorderLayout.CENTER);
            JLabel lavagem = new JLabel("Lavagem");
            botaoPedido.add(lavagem, BorderLayout.CENTER);
            JLabel secagem = new JLabel("Secagem");
            botaoPedido.add(secagem, BorderLayout.CENTER);
            jPanel1.add(botaoPedido);
        }
    }

    private void adicionarNovoPedido() {
        // Verifica se todos os botões de pedidos já foram usados
        if (contadorPedidos >= botoesPedidos.size()) {
            System.out.println("Tentando setar o valor");
            jLabel1.setText("Há mais pedidos na fila de espera");
            jLabel1.setVisible(true);
            return;
        }

        // Torna o próximo botão de pedido visível
        botoesPedidos.get(contadorPedidos).setVisible(true);
        contadorPedidos++;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(940, 660));
        setResizable(false);
        setSize(new java.awt.Dimension(940, 660));
        getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("SERVIÇOS - ÁREA SUJA");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 20, 880, 36);

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("SAIR");
        getContentPane().add(jButton3);
        jButton3.setBounds(340, 550, 240, 60);

        jPanel1.setLayout(new java.awt.GridLayout(2, 4, 15, 15));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 80, 880, 430);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 520, 880, 0);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/user.png"))); // NOI18N
        jLabel5.setText("MAS0481");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(790, 30, 100, 16);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioAreaSujaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioAreaSujaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioAreaSujaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioAreaSujaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioAreaSujaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
